=== eiansiah/IP_Practical/Eddie/Practical4/Q4Corrected/trainers.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT trainers (trainer+)>
<!ELEMENT trainer (name, qualifications+)>
<!ATTLIST trainer trainerID ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT qualifications (title, institution, year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== eiansiah/IP_Practical/Eddie/Practical4/Q4Corrected/trainers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trainers SYSTEM "trainers.dtd" >
<trainers>
    <trainer trainerID="T1">
        <name>John Doe</name>
        <qualifications>
            <title>Master in PHP</title>
            <institution>UTM</institution>
            <year>2015</year>
        </qualifications>
        <qualifications>
            <title>Certified PHP Programmer</title>
            <institution>PHP Net</institution>
            <year>2020</year>
        </qualifications>
    </trainer>
</trainers>
