=== eiansiah/IP_Practical/Saw/practical4Q7/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="contacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="contact" type="contactType" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="contactType">
        <xs:sequence>
            <xs:element name="name" type="nameType" />
            <xs:element name="phone" type="phoneType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="knows" type="knowsType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="personID" type="xs:ID" use="required" />
        <xs:attribute name="gender" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="male" />
                    <xs:enumeration value="female" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="first" maxOccurs="unbounded" type="xs:string" />
            <xs:element name="middle" minOccurs="0" type="xs:string" />
            <xs:element name="last" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="phoneType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="kind" use="optional">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Home" />
                            <xs:enumeration value="Work" />
                            <xs:enumeration value="Cell" />
                            <xs:enumeration value="Fax" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="knowsType">
        <xs:sequence />
        <xs:attribute name="contact" type="xs:IDREFS" />
    </xs:complexType>
</xs:schema>

=== eiansiah/IP_Practical/E-Ian/Practical4/PartA/Q6/contactsQ6.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='contacts.xsd'>
    <contact personID="P001">
        <name>
            <first>Saw</first>
            <first>Khoo</first>
            <middle>Zi</middle>
            <last>Chong</last>
        </name>
        <phone kind="Home">0351457895</phone>
        <knows contact="P002 P003"/>
    </contact>
    <contact personID="P002">
        <name>
            <first>Sim</first>
            <middle>Hor</middle>
            <last>Kang</last>
        </name>
        <phone kind="Cell">0115479633</phone>
        <knows contact="P001 P003"/>
    </contact>
    <contact personID="P003">
        <name>
            <first>Christopher Yap</first>
            <last>Jian Xing</last>
        </name>
        <phone kind="Cell">0157489588</phone>
        <knows contact="P001 P002"/>
    </contact>
</contacts>

=== eiansiah/IP_Practical/Saw/practical4Q7/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contacts.xsd">
    <contact personID="c1" gender="male">
        <name>
            <first>Ali</first>
            <middle>Bin</middle>
            <last>Abu</last>
        </name>
        <knows contact="c2 c3"/>
    </contact>
    <contact personID="c2" gender="female">
        <name>
            <first>Ali</first>
            <last>Abu</last>
        </name>
        <phone kind="Home">234-567-8901</phone>
        <phone kind="Home">234-567-8901</phone>
        <phone kind="Home">234-567-8901</phone>
        <knows contact="c1"/>
    </contact>
    <contact personID="c3" gender="male">
        <name>
            <first>Ah</first>
            <first>Beng</first>
            <middle>Bin</middle>
            <last>Abu</last>
        </name>
        <phone kind="Cell">345-678-9012</phone>
        <knows contact="c1"/>
    </contact>
</contacts>
