=== eiansiah/IP_Practical/E-Ian/Practical4/PartA/Q4/trainers.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT trainers (trainer*)>
<!ELEMENT trainer (name, qualifications*)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST trainer trainerID ID #REQUIRED>
<!ELEMENT qualifications (qualification*)>
<!ELEMENT qualification (title, institution, year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== eiansiah/IP_Practical/Saw/practical4Q4/trainers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trainers SYSTEM "trainers.dtd">
<trainers>
  <trainer trainerID="T001">
    <name>Ali Abu</name>
    <qualifications>
      <qualification>
        <title>Master Trainer</title>
        <institution>Training Academy</institution>
        <year>2015</year>
      </qualification>
      <qualification>
        <title>Yoga Instructor</title>
        <institution>Yoga Institute</institution>
        <year>2018</year>
      </qualification>
    </qualifications>
  </trainer>
  <trainer trainerID="T002">
    <name>Sara</name>
    <qualifications>
      <qualification>
        <title>Fitness Expert</title>
        <institution>Health University</institution>
        <year>2020</year>
      </qualification>
    </qualifications>
  </trainer>
</trainers>

=== eiansiah/IP_Practical/E-Ian/Practical4/PartA/Q4/trainers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE trainers SYSTEM "trainers.dtd" >
<trainers>
    <trainer trainerID="T1">
        <name>John Doe</name>
        <qualifications>
            <qualification>
                <title>Master in PHP</title>
                <institution>UTM</institution>
                <year>2015</year>
            </qualification>
            <qualification>
                <title>Certified PHP Programmer</title>
                <institution>PHP Net</institution>
                <year>2020</year>
            </qualification>
        </qualifications>
        <qualifications>
            <qualification>
                <title>Doctorate in PHP</title>
                <institution>UTM</institution>
                <year>2025</year>
            </qualification>
        </qualifications>
    </trainer>

    <trainer trainerID="T2">
        <name>Eddie Sim</name>
        <qualifications>
            <qualification>
                <title>Bachelor Degree in Java</title>
                <institution>UM</institution>
                <year>2011</year>
            </qualification>
            <qualification>
                <title>Certified Java Programmer</title>
                <institution>Java</institution>
                <year>2015</year>
            </qualification>
        </qualifications>
        <qualifications>
            <qualification>
                <title>Master in Java</title>
                <institution>UM</institution>
                <year>2020</year>
            </qualification>
        </qualifications>
    </trainer>
</trainers>
