=== eiansiah/IP_Practical/Saw/practical4Q3/contacts.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT contacts (contact*)>
<!ELEMENT contact (name, phone*, website*, email+, knows)>
<!ATTLIST contact personID ID #REQUIRED gender (male | female) #REQUIRED>
<!ELEMENT name (first+, middle?, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone kind (Home | Work | Cell | Fax) "Home">
<!ELEMENT website (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT knows EMPTY>
<!ATTLIST knows contact IDREFS #IMPLIED>

=== eiansiah/IP_Practical/Saw/practical4Q3/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts SYSTEM "contacts.dtd">
<contacts>
    <contact personID="c1" gender="male">
        <name>
            <first>Ali</first>
            <middle>Bin</middle>
            <last>Abu</last>
        </name>
        <phone kind="Work">123-456-7890</phone>
        <website>http://ali.com</website>
        <email>Ali@email.com</email>
        <email>Abu@email.com</email>
        <knows contact="c2 c3"/>
    </contact>
    <contact personID="c2" gender="female">
        <name>
            <first>Ali</first>
            <last>Abu</last>
        </name>
        <phone kind="Home">234-567-8901</phone>
        <email>Abu@email.com</email>
        <knows contact="c1"/>
    </contact>
    <contact personID="c3" gender="male">
        <name>
            <first>Ah</first>
            <first>Beng</first>
            <middle>Bin</middle>
            <last>Abu</last>
        </name>
        <phone kind="Cell">345-678-9012</phone>
        <website>http://ali.com</website>
        <email>Abu@email.com</email>
        <knows contact="c1"/>
    </contact>
</contacts>
